=== badf00d21/xml_projekat/Parliament/Parliament.DataAccess/XmlSchema/Propis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.parliament.rs/schema" xmlns="http://www.parliament.rs/schema"
    xmlns:parliament="http://www.parliament.rs/schema"
    xmlns:security="http://www.w3.org/2000/09/xmldsig#">
    <xs:include schemaLocation="NadlezniOrgan.xsd"/>
    <xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
        schemaLocation="http://www.w3.org/2000/09/xmldsig"/>
    <xs:element name="Propis">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Preambula" minOccurs="1"/>
                <xs:element name="NazivPropisa">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="300"/>
                            <xs:pattern value="[A-Z][A-Z ]{0,300}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" ref="Deo"/>
                    <xs:element maxOccurs="unbounded" minOccurs="1" ref="Glava"/>
                    <xs:element maxOccurs="20" minOccurs="2" ref="Clan"/>
                </xs:choice>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Prilog" type="xs:string"/>
                <xs:element ref="security:Signature"/>
            </xs:sequence>
            <xs:attribute ref="DatumVremePredlaganja" use="required"/>
            <xs:attribute ref="DatumVremeUsvajanja" use="optional"/>
            <xs:attribute name="SerijskiBroj" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Preambula">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PravniOsnov" type="xs:string" minOccurs="0"/>
                <xs:element ref="NadlezniOrgan"/>
                <xs:element minOccurs="0" ref="Saglasnost"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Saglasnost" nillable="false">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naznaka" type="xs:string"/>
                <xs:element ref="NadlezniOrgan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NazivDela">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="500"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element maxOccurs="unbounded" ref="Glava" minOccurs="2"/>
            </xs:sequence>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glava">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NazivGlave">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="500"/>
                            <xs:pattern value="[A-Z][A-Z ]{0,300}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element maxOccurs="unbounded" ref="Odeljak"/>
            </xs:sequence>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NazivOdeljka">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="30"/>
                            <xs:pattern value="[1-9][0-9]*\. [A-Za-z ]*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:choice>
                    <xs:element maxOccurs="unbounded" ref="Pododeljak"/>
                    <xs:element maxOccurs="unbounded" ref="Clan"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pododeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NazivPododeljka">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="300"/>
                            <xs:pattern value="\([a-z]\) [A-Za-z ]*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element maxOccurs="unbounded" ref="Clan"/>
            </xs:sequence>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NazivClana">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="300"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:choice>
                    <xs:element ref="TekstualniSadrzaj"/>
                    <xs:element maxOccurs="unbounded" ref="Stav"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stav">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="TekstualniSadrzaj"/>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="Tacka"/>
            </xs:choice>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Tacka">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="TekstualniSadrzaj"/>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="Podtacka"/>
            </xs:choice>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podtacka">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="TekstualniSadrzaj"/>
                <xs:element maxOccurs="unbounded" minOccurs="2" name="Alineja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="Id" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute ref="RedniBroj" use="required"/>
            <xs:attribute ref="Id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="TekstualniSadrzaj" type="xs:string"/>
    <xs:attribute name="RedniBroj" type="xs:positiveInteger"/>
    <xs:attribute name="Id" type="xs:ID"/>
    <xs:attribute name="DatumVremePredlaganja" type="xs:dateTime"/>
    <xs:attribute name="DatumVremeUsvajanja" type="xs:dateTime"/>
</xs:schema>

=== badf00d21/xml_projekat/Parliament/Parliament.DataAccess/XmlSchema/instance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<parliament:Propis xmlns:parliament="http://www.parliament.rs/schema"
 xmlns:security="http://www.w3.org/2000/09/xmldsig#"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.parliament.rs/schema file:/D:/GitHubRepos/xml_projekat/Parliament/Parliament.DataAccess/XmlSchema/Propis.xsd" parliament:DatumVremePredlaganja="2006-05-04T18:13:51.0" SerijskiBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
    <parliament:Preambula>
        <parliament:NadlezniOrgan Uloga="Odbornik">
            <parliament:Ime>AA</parliament:Ime>
            <parliament:Prezime>AA</parliament:Prezime>
            <parliament:Email>0@0.0</parliament:Email>
        </parliament:NadlezniOrgan>
    </parliament:Preambula>
    <parliament:NazivPropisa>A</parliament:NazivPropisa>
    <parliament:Deo parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
        <parliament:NazivDela>NazivDela0</parliament:NazivDela>
        <parliament:Glava parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
            <parliament:NazivGlave>A</parliament:NazivGlave>
            <parliament:Odeljak parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                <parliament:NazivOdeljka>1. </parliament:NazivOdeljka>
                <parliament:Pododeljak parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                    <parliament:NazivPododeljka>(a) </parliament:NazivPododeljka>
                    <parliament:Clan parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                        <parliament:NazivClana>NazivClana0</parliament:NazivClana>
                        <parliament:TekstualniSadrzaj>TekstualniSadrzaj0</parliament:TekstualniSadrzaj>
                    </parliament:Clan>
                    <parliament:Clan parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                        <parliament:NazivClana>NazivClana1</parliament:NazivClana>
                        <parliament:Stav parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                            <parliament:TekstualniSadrzaj>TekstualniSadrzaj1</parliament:TekstualniSadrzaj>
                        </parliament:Stav>
                        <parliament:Stav parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                            <parliament:TekstualniSadrzaj>TekstualniSadrzaj2</parliament:TekstualniSadrzaj>
                        </parliament:Stav>
                    </parliament:Clan>
                </parliament:Pododeljak>
                <parliament:Pododeljak parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                    <parliament:NazivPododeljka>(a) </parliament:NazivPododeljka>
                    <parliament:Clan parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                        <parliament:NazivClana>NazivClana2</parliament:NazivClana>
                        <parliament:Stav parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                            <parliament:Tacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja0</parliament:Alineja>
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja1</parliament:Alineja>
                                </parliament:Podtacka>
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:TekstualniSadrzaj>TekstualniSadrzaj3</parliament:TekstualniSadrzaj>
                                </parliament:Podtacka>
                            </parliament:Tacka>
                            <parliament:Tacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:TekstualniSadrzaj>TekstualniSadrzaj4</parliament:TekstualniSadrzaj>
                                </parliament:Podtacka>
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja2</parliament:Alineja>
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja3</parliament:Alineja>
                                </parliament:Podtacka>
                            </parliament:Tacka>
                        </parliament:Stav>
                        <parliament:Stav parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                            <parliament:Tacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                <parliament:TekstualniSadrzaj>TekstualniSadrzaj5</parliament:TekstualniSadrzaj>
                            </parliament:Tacka>
                            <parliament:Tacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                <parliament:TekstualniSadrzaj>TekstualniSadrzaj6</parliament:TekstualniSadrzaj>
                            </parliament:Tacka>
                        </parliament:Stav>
                    </parliament:Clan>
                    <parliament:Clan parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                        <parliament:NazivClana>NazivClana3</parliament:NazivClana>
                        <parliament:Stav parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                            <parliament:Tacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja4</parliament:Alineja>
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja5</parliament:Alineja>
                                </parliament:Podtacka>
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja6</parliament:Alineja>
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja7</parliament:Alineja>
                                </parliament:Podtacka>
                            </parliament:Tacka>
                            <parliament:Tacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja8</parliament:Alineja>
                                    <parliament:Alineja parliament:Id="00000000-0000-0000-0000-000000000000">Alineja9</parliament:Alineja>
                                </parliament:Podtacka>
                                <parliament:Podtacka parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                                    <parliament:TekstualniSadrzaj>TekstualniSadrzaj7</parliament:TekstualniSadrzaj>
                                </parliament:Podtacka>
                            </parliament:Tacka>
                        </parliament:Stav>
                        <parliament:Stav parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                            <parliament:TekstualniSadrzaj>TekstualniSadrzaj8</parliament:TekstualniSadrzaj>
                        </parliament:Stav>
                    </parliament:Clan>
                </parliament:Pododeljak>
            </parliament:Odeljak>
            <parliament:Odeljak parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                <parliament:NazivOdeljka>1. </parliament:NazivOdeljka>
                <parliament:Clan parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                    <parliament:NazivClana>NazivClana4</parliament:NazivClana>
                    <parliament:TekstualniSadrzaj>TekstualniSadrzaj9</parliament:TekstualniSadrzaj>
                </parliament:Clan>
                <parliament:Clan parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
                    <parliament:NazivClana>NazivClana5</parliament:NazivClana>
                    <parliament:TekstualniSadrzaj>TekstualniSadrzaj10</parliament:TekstualniSadrzaj>
                </parliament:Clan>
            </parliament:Odeljak>
        </parliament:Glava>
        <parliament:Glava parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
            <parliament:NazivGlave>A</parliament:NazivGlave>
            <parliament:Odeljak parliament:RedniBroj="50" parliament:Id="00000000-0000-0000-0000-000000000000">
